endpoint: http://dbpedia.org/sparql
owlFile: ./dbpieda-ontology.owl
seed: 123
types:
  - http://dbpedia.org/ontology/Politician
  - http://dbpedia.org/ontology/Company
  - http://dbpedia.org/ontology/ArchitecturalStructure
  - http://dbpedia.org/ontology/Architect
percentageOfPositiveExamples: 0.5
percentageOfNegativeExamples: 0.5
maxNoOfExamples: 30
minNoOfExamples: 5
maxGenerateConcepts: 10
maxConceptLength: 20
maxDepth: 3
