endpoint: https://sparql.uniprot.org/sparql
owlFile: ./uniprot.owl
seed: 123
types:
  - http://purl.uniprot.org/core/Journal_Citation
  - http://purl.uniprot.org/core/Genomic_RNA
  - http://purl.uniprot.org/core/Gene
  - http://purl.uniprot.org/core/Enzyme
  - http://purl.uniprot.org/core/Disease
  - http://purl.uniprot.org/core/DNA
  - http://purl.uniprot.org/core/Journal
  - http://purl.uniprot.org/core/MRNA
  - http://purl.uniprot.org/core/Part
  - http://purl.uniprot.org/core/Protein
  - http://purl.uniprot.org/core/Sequence
  - http://purl.uniprot.org/core/Cluster
  - http://www.w3.org/2002/07/owl#Thing #will be allowed, but not actively used!
maxNoOfIndividuals: 5
maxIndividualsPerExampleConcept: 30
percentageOfPositiveExamples: 0.5
percentageOfNegativeExamples: 0.5
maxNoOfExamples: 30
minNoOfExamples: 5
maxGenerateConcepts: 20

#maxDepth: 2
#maxConceptLength: 8
#minConceptLength: 4
#inferDirectSuperClasses: true
#endpointInfersRules: false