name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses:
      - shell: bash
        run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout > version.log
      - run: pip install mkdocs-material
      - run: pip install mkdocs-macros-plugin
      - run: sed -i "s/\$VERSION/$(cat version.log)/g" mkdocs.yml
      - run: mkdocs gh-deploy --force -d site/$(cat version.log)
      - run: mvn javadoc:javadoc
